pipeline {
    agent any

    tools {
        maven 'Maven 3.6.1'
    }
    
    stages {
        stage ('worker-build') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage ('worker-test') {
            when {
                chagneset '**/worker/**'
            }
            steps {
                echo 'Running Unit Tests on worker app'
                dir ('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage ('worker-package') {
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging worker app'
                dir ('worker') {
                    sh 'mvn package -D skipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline for worker is complete..'
        }
    }
}